matrix:
  include:
    # Plain Agent
    - os: linux
      env:
        - CONFIGURE=""
    # TLS Agent
    - os: linux
      env:
        - CONFIGURE="--enable-tls --enable-ssl"      
    # SSL Agent
    - os: linux
      env:
        - CONFIGURE="--enable-ssl"      

language: c

compiler:
  - gcc

install: 
  - sudo -E apt-add-repository -y ppa:linuxjedi/ppa
  - sudo apt-get update || true
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y libpcap-dev libexpat-dev libjson0-dev bison flex libtool autoconf automake autogen libuv-dev libssl-dev libgcrypt20 libgcrypt20-dev 
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install -r mocha

script:
  - ./build.sh
  - ./configure ${CONFIGURE}
  - make
  - ./src/captagent -h
  - ./src/captagent -v
  - cd test && npm install && sudo npm test
